services:
  postgres:
    image: postgres:15
    container_name: pro-postgres-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: pro-app-1
    restart: always

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

    ports:
      - "3000:3000"

    volumes:
      - /var/www/iarko/uploads:/app/uploads

    # ✅ ВАЖНО: убрали sleep и inline command
    command: sh ./docker-entrypoint.sh

volumes:
  postgres_data: