services:
  postgres:
    image: postgres:15
    container_name: pro-postgres-1
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: y198619
      POSTGRES_DB: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true   # 🔥 важно: всегда пересборка

    container_name: pro-app-1
    restart: always

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql://postgres:y198619@postgres:5432/postgres

    ports:
      - "127.0.0.1:3000:3000"

    volumes:
      - ./uploads:/app/uploads

    env_file:
      - .env

volumes:
  postgres_data: